name: "Build KMP App on Main"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Full KMP Build (shared + Android)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build Shared Module
        run: ./gradlew :shared:build

      - name: Run Unit Tests for Shared Code
        run: ./gradlew :shared:test

      - name: Build Android App Release
        run: ./gradlew :androidApp:assembleRelease
